services:
  # MongoDB service
  mongodb:
    image: mongo:6.0
    container_name: mealloop-mongodb
    restart: unless-stopped
    environment:
      - MONGO_INITDB_DATABASE=mealloop
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"
    networks:
      - mealloop_network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "'db.runCommand({ ping: 1 })'", "localhost:27017/test"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s

  # Backend service
  backend:
    build:
      context: ./backend
      target: ${NODE_ENV:-development}
    container_name: mealloop-backend
    restart: unless-stopped
    depends_on:
      mongodb:
        condition: service_healthy
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      - MONGO_URI=mongodb://mongodb:27017/mealloop
      - PORT=5000
      - JWT_SECRET=${JWT_SECRET:-mealloop_secure_key_2025_!@#$%^&*()}
      - FRONTEND_URL=http://frontend:5173  # Use container name instead of localhost
    volumes:
      - ./backend:/app
      - /app/node_modules
    ports:
      - "5000:5000"
    networks:
      - mealloop_network
    command: npm run ${NODE_ENV:-dev}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s

  # Frontend service
  frontend:
    build:
      context: ./frontend/mealloop
      target: ${NODE_ENV:-development}
    container_name: mealloop-frontend
    restart: unless-stopped
    depends_on:
      backend:
        condition: service_healthy
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      - VITE_API_BASE_URL=http://localhost:5000/api  # Use localhost for browser access
      - VITE_CLOUDINARY_CLOUD_NAME=${CLOUDINARY_CLOUD_NAME:-ddiqp1bzn}
      - VITE_CLOUDINARY_UPLOAD_PRESET=${CLOUDINARY_UPLOAD_PRESET:-mealloop_preset}
      - VITE_GOOGLE_MAPS_API_KEY=${GOOGLE_MAPS_API_KEY:-AIzaSyAOmY0mUFLHWgl5MCaBsGvpDucrH5mwLr8}
    volumes:
      - ./frontend/mealloop:/app
      - /app/node_modules
    ports:
      - "3000:5173" # Maps host port 3000 to container port 5173 for development
    networks:
      - mealloop_network
    stdin_open: true  # Keep STDIN open for interactive processes
    tty: true  # Allocate a pseudo-TTY
    command: npm run dev
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "5173"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s

# Define volumes
volumes:
  mongodb_data:
    driver: local

# Define networks
networks:
  mealloop_network:
    driver: bridge
